### PR TITLE
Switches back-end API for client side pages

### LINKED ISSUE #504: Adding sections and web parts to the modern pages is not working
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.7]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question

The sections and OOB web parts should be added in the newly created site pages.

### Observed Behavior

I am loading the site in the Web object and adding the client side page using the web object. Once the page got created I am adding sections, columns & web parts to the page, finally I am saving the page. The created page was holding the sections and web parts which was added programmatically, but all of sudden the sections and the web parts not appearing. I am not getting any errors but the sections are not getting added for the newly created pages.

**The page is getting created but the sections and web parts are not getting added.**

### Steps to Reproduce

The code I am using for creating page and adding web parts:

```
(async () => {
     var web = new Web("https://tenant.sharepoint.com/sites/test");
     const page = await web.addClientSidePage("test.aspx", "My site Page");
     const section = page.addSection();
     const column = section.addColumn(4);
     const column1 = section.addColumn(4);
     const column2 = section.addColumn(4);
     await page.save();
    })().then(_ => {
    }).catch(
      error => console.log(error)
    );
```

**After the page.save() it is returning the item with empty CanvasContent1**

item: Item
Approved_x0020_byId: null
Approved_x0020_byStringId: null
AuthorId: 10
BannerImageUrl: {Description: "/_layouts/15/images/sitepagethumbnail.png", 
Url: "https://tenant.sharepoint.com/_layouts/15/images/sitepagethumbnail.png"}
**CanvasContent1: null**

Could you please help me with any suggestion/solution.

### PR DESCRIPTION
**Pull request by patrick-rodgers**
#### Category
- [X] Bug fix?
- [X] New feature?
- [ ] New sample?
- [ ] Documentation update?

#### Related Issues

fixes #504 

#### What's in this Pull Request?

This PR switches the back-end API used to process client page related requests such as loading modern pages, updating sections, columns, & controls.

Best effort was made to mimic previous API and folks using the core methods shouldn't notice a difference.

Also adds support for updating a few of the modern page settings. We can expand this later, but focus for this PR is to fix the issue blocking folks.

### CODE REVIEW

File: packages/sp/src/clientsidepages.ts [hunk 1]
```diff
@@ -440,12 +475,46 @@ export class ClientSidePage extends File {
...
      * Get the liked by information for a modern site page     
      */
-    public getLikedByInformation(): Promise<void> {
+    public getLikedByInformation(): Promise<any> {
         return this.getItem().then(i => {
             return i.getLikedByInformation();
         });
     }
 
+    protected getCancasContent1(): string {
```
Comment (waldekmastykarz) [inline packages/sp/src/clientsidepages.ts]: Seems like a typo. Should it be `getCanvasContent1`?

Comment (patrick-rodgers) [reply packages/sp/src/clientsidepages.ts]: NO, in my country we spell it Cancas. Duh.

(yes, fixed it, thanks :) )
