### PR TITLE
Full audit of presets/all imports

### LINKED ISSUE #3216: .batched() not recognized in "@pnp/sp/presets/all"
### Major Version

4.x

### Minor Version Number

4.10.0

### Target environment

All

### Additional environment details

Bun blank template
Or Node and tsc --init

### Expected or Desired Behavior

`.batched()` should be recognized;

### Observed Behavior

TS is reporting an error however the method is available.

### Steps to Reproduce

`bun init`
`Blank`
`bun i @pnp/sp`

OR
`npm --init`
`tsc --init`
`npm i @pnp/sp`

```ts
import { spfi } from "@pnp/sp/presets/all"

const a = spfi("")
a.web.batched() //error
```
while
```ts
import { spfi } from "@pnp/sp/presets/all"
import type {} from "@pnp/sp/batching"
const a = spfi("")
a.web.batched();
```
works

### PR DESCRIPTION
**Pull request by juliemturner**
### Category

- [x] Bug fix?
- [ ] New feature?
- [ ] New sample?
- [ ] Documentation update?

### Related Issues

fixes #3216

### What's in this Pull Request?

Performed audit of SP/Presets/All and Graph/Presets/All to update any missing imports.

### CODE REVIEW

File: packages/graph/presets/all.ts [hunk 1]
```diff
@@ -21,6 +21,7 @@ import "../lists/index.js";
 import "../mail/index.js";
 import "../members/index.js";
 import "../onenote/index.js";
+import "../open-extensions/index.js";
```
Comment (patrick-rodgers) [inline packages/graph/presets/all.ts:24]: open extensions don't exist yet. we can merge this - but the api support isn't there yet.

File: packages/graph/presets/all.ts [hunk 2]
```diff
@@ -35,41 +36,45 @@ import "../taxonomy/index.js";
...
+export * from "../files/index.js";
+export * from "../groups/index.js";
+export * from "../insights/index.js";
+export * from "../invitations/index.js";
+export * from "../list-item/index.js";
+export * from "../lists/index.js";
+export * from "../mail/index.js";
+export * from "../members/index.js";
+export * from "../onenote/index.js";
+export * from "../open-extensions/index.js";
```
Comment (patrick-rodgers) [inline packages/graph/presets/all.ts:65]: same as above on open extensions

**Review by patrick-rodgers — APPROVED** [review]
