### PR TITLE
fix getParentWeb method

### LINKED ISSUE #441: GetParentWeb method throwing error
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

@pnp/sp: [    "1.2.7"     ]

SharePoint version: [    SPFx     ]

### Expected / Desired Behavior / Question
I'm trying to use the getParentSite() method.

### Observed Behavior
imagem

It's throwing this error. I have set up the context as such:

  sp.setup({
    spfxContext: context  
  });

Context is this.context coming from the onInit method of my ApplicationCustomizer. (SPFx Extension)

### Steps to Reproduce
Just try using the method on SPFx.

Thanks!

### PR DESCRIPTION
**Pull request by tavikukko**
#### Category
- [x] Bug fix?
- [ ] New feature?
- [ ] New sample?
- [ ] Documentation update?

#### Related Issues

fixes #441

#### What's in this Pull Request?

There was error constructing new Site. Also if Web is rootWeb, it does not have ParentWeb, so made it to return null in that case.

### CODE REVIEW

File: packages/sp/src/webs.ts [hunk 1]
```diff
@@ -111,7 +111,7 @@ export class Web extends SharePointQueryableShareableWeb {
      */
     public getParentWeb(): Promise<{ data: any; web: Web }> {
         return this.select("ParentWeb/Id").expand("ParentWeb").get()
-            .then(({ ParentWeb }) => new Site(this.toUrlAndQuery().split("/_api")[0]).openWebById(ParentWeb.Id));
+            .then(({ ParentWeb }) => ParentWeb ? new Site(this.parentUrl).openWebById(ParentWeb.Id) : null);
```
Comment (patrick-rodgers) [inline packages/sp/src/webs.ts]: Why not here just get the ParentWeb/Url and return a new web that way? I am sure I wrote the old code, but looking at it I think we can come up with a better way.

Comment (tavikukko) [reply packages/sp/src/webs.ts]: Here a previous discussion about the implementation #69

Comment (patrick-rodgers) [reply packages/sp/src/webs.ts]: Oh right, ParentWeb isn't a web instance but WebInformation instance. Got it.
